# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('kind', models.SmallIntegerField(choices=[(0, 'organization'), (10, 'manager'), (100, 'unavailable'), (90, 'scheduled unavailable')], default=0, verbose_name='Interval kind')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('kind',),
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_extended_date', models.DateTimeField(null=True)),
                ('fulltime_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulltime_resources', to='rcalendar.Organization')),
                ('parttime_organizations', models.ManyToManyField(related_name='parttime_resources', to='rcalendar.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceScheduleInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_intervals', to='rcalendar.Resource')),
            ],
            options={
                'ordering': ('resource', 'day_of_week'),
            },
        ),
        migrations.AddField(
            model_name='manager',
            name='organizations',
            field=models.ManyToManyField(related_name='managers', to='rcalendar.Organization'),
        ),
        migrations.AddField(
            model_name='interval',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_intervals', to='rcalendar.Manager'),
        ),
        migrations.AddField(
            model_name='interval',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_intervals', to='rcalendar.Organization'),
        ),
        migrations.AddField(
            model_name='interval',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='rcalendar.Resource'),
        ),
    ]
