# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='app',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='app',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='msa_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='app',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='msa_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='app',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='msa_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
