# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcalendar', '0002_auto_20160912_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_extended_date', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_members', to='rcalendar.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_intervals', to='rcalendar.ResourceMembership')),
            ],
            options={
                'ordering': ('membership', 'day_of_week'),
            },
        ),
        migrations.RemoveField(
            model_name='resourcescheduleinterval',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='fulltime_organization',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='parttime_organizations',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='schedule_extended_date',
        ),
        migrations.AlterField(
            model_name='interval',
            name='kind',
            field=models.SmallIntegerField(choices=[(0, 'organization'), (10, 'manager'), (100, 'unavailable')], default=0, verbose_name='Interval kind'),
        ),
        migrations.DeleteModel(
            name='ResourceScheduleInterval',
        ),
        migrations.AddField(
            model_name='resourcemembership',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='rcalendar.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcemembership',
            unique_together=set([('resource', 'organization')]),
        ),
    ]
