debug: true

# DJANGO ALLOWED_HOSTS
hosts:
  - localhost
  - rcalendar-dev
  - rcalendar.marfa.team
  - calendar.marfa.team
  - calendar.marfa.dev

internal_ips:
  - 127.0.0.1

db:
  engine: django.db.backends.postgresql
  host: postgres
  port: 5432
  database: msa_rcalendar
  user: msa_rcalendar
  password: msa_rcalendar


# INTERNAL PROJECT SETTINGS
common:
  base:
    host: rcaldendar.marfa.dev
    port: 8000
    scheme: http
